version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "my_database"
      MYSQL_USER: "my_user"
      MYSQL_PASSWORD: "my_password"
    ports:
      - "3309:3309"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "8081:80"

volumes:
  mysql_data:
